plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
}
version = mod_version
group = mod_group_id
base.archivesName = mod_id
java.toolchain.languageVersion = JavaLanguageVersion.of(25)
neoForge {
    version = neo_version
    runs {
        configureEach {
            gameDirectory = file(providers.gradleProperty("runDir").getOrElse("run"))
        }
        client { client() }
        server { server(); programArgument '--nogui' }
        data {
            clientData()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources').absolutePath, '--existing', file('src/main/resources').absolutePath
        }
    }
    mods {
        "${mod_id}" { sourceSet(sourceSets.main) }
    }
}
sourceSets.main.resources { srcDir 'src/generated/resources' }
repositories {
    maven { url = 'https://api.modrinth.com/maven'; content { includeGroup 'maven.modrinth' } }
    mavenCentral()
}
dependencies {
    implementation "maven.modrinth:geckolib:${geckolib_version_id}"
}
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('processResources', ProcessResources) {
    var replaceProperties = [minecraft_version_range: minecraft_version_range, neo_version: neo_version,
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
        mod_authors: mod_authors, mod_description: mod_description, geckolib_version: geckolib_version]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) { expand replaceProperties }
}
publishing {
    publications { mavenJava(MavenPublication) { from components.java } }
    repositories { maven { url = layout.projectDirectory.dir('mcmodsrepo') } }
}
idea.module { downloadJavadoc = downloadSources = true }

