org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false


minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.6
forge_version_range=[50,)
loader_version_range=[50,)
mapping_channel=parchment
mapping_version=2024.11.17-1.21.1


mod_id=quakeweapons
mod_name=Quake Weapons
mod_license=All Rights Reserved
mod_version=1v
mod_group_id=mett.palemannie.quakeweapons
mod_authors=Pale Mannie, Knocks Schiller
mod_description=A Mod containing every weapon and powerup from Quake 1

geckolib_version=4.8.2