org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false


minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.252
neo_version_range=[21.1.252,)
loader_version_range=[4,)


mod_id=quakeweapons
mod_name=Quake Weapons
mod_license=All Rights Reserved
mod_version=3v-1.21.1-neoforge
mod_group_id=mett.palemannie.quakeweapons
mod_authors=Pale Mannie, Knocks Schiller, Skidmark
mod_description=A Mod containing every weapon and powerup from Quake 1

geckolib_version=4.7.3
