org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.39-beta

mod_id=quakeweapons
mod_name=Quake Weapons
mod_license=All Rights Reserved

mod_version=3v-26.3-neoforge
mod_group_id=mett.palemannie.quakeweapons
mod_authors=Pale Mannie, Knocks Schiller, Skidmark
mod_description=A Mod containing every weapon and powerup from Quake 1

geckolib_version=5.5.7
geckolib_version_id=2s1O42FX
